NUM_GPUS: 1
SAVE_INTERVAL: 10
VALIDATE_INTERVAL: 50
LOG_DIR: "logs"
TRIAL: "trial_01"
WEIGHTS: "test.weights"

DATASET:
  TRAIN:
    CROP_SIZE: [256, 256]
    SCALE_FROM: 1.0
    SCALE_TO: 1.0
    APPLY_TRANSFORM: True
  VALIDATE:
    CROP_SIZE: [256, 256]
    SCALE_FROM: 1.0
    SCALE_TO: 1.0
    APPLY_TRANSFORM: False

TRAIN:
  BATCH_SIZE: 2
  PRETRAIN_BATCH_SIZE: 2
  NUM_EPOCHS: 2000
  NUM_WORKERS: 1
  NUM_PRETRAIN: 2000
  CONTINUE: False

VALIDATE:
  BATCH_SIZE: 4
  CRF_PROCESS: False
  NUM_WORKERS: 1

NET:
  LR: 0.0001
  WEIGHT_DECAY: 0.0005
  MASK_LOSS_BCE: 0.1
  LOWER_LIMIT: 0.4
  PAMR_ITER: 10
  BACKBONE_PRETRAINED: True
